<h1><center>Laboratorio 8: Aprendizaje Supervisado 🔮</center></h1>

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos</strong></center>

### Cuerpo Docente:

- Profesor: Pablo Badilla y Ignacio Meza
- Auxiliar: Sebastián Tinoco
- Ayudante: Felipe Arias y Diego Cortez

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: Canela Orellana
- Nombre de alumno 2: Isabel Marx


### **Link de repositorio de GitHub:** https://github.com/CanelaOrellana/MDS7202-IsabelMarx-y-CanelaOrellana

## Temas a tratar

- Aprendizaje Supervisado
- Flujos de datos a través de `Pipelines`.

## Reglas

- **Grupos de 2 personas**
- Asistencia **obligatoria** a instrucciones del lab (viernes 16.15). Luego, pueden quedarse trabajando en las salas o irse.
- **No se revisarán entregas de personas ausentes**. 
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Prohibidas las copias. 
- Pueden usar cualquer matrial del curso que estimen conveniente.

## Objetivos principales del laboratorio

- Comprender el funcionamiento de clasificadores/regresores.
- Generar múltiples modelos predictivos.
- Comprender las ventajas de crear modelos en pipeline vs hacer las operaciones a mano.

El laboratorio deberá ser desarrollado sin el uso indiscriminado de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`, las cuales vale mencionar, son bastante más eficientes que los iteradores nativos sobre `DataFrames`.

### Importamos librerias utiles 😸

In [1]:
# Libreria Core del lab.
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split 

# Pre-procesamiento
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

# Metricas de evaluación
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score

#Libreria para plotear
!pip install --upgrade plotly
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.5/15.5 MB 66.9 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.13.1
    Uninstalling plotly-5.13.1:
      Successfully uninstalled plotly-5.13.1


https://www.kaggle.com/antoinekrajnc/soccer-players-statistics

# 1. Predicciones Futboleras

<p align="center">
  <img src="https://drive.google.com/uc?export=view&id=1BnO4tyh3vM2P199Ec9s3JjngQ4qQ9seP"
" width="300">
</p>


Tras el trágico despido de la mítica mascota de Maipú, Renacín decide adentrarse como consultor en el mercado futbolero, el cuál (para variar...) está cargado en especulaciones. 

Como su principal tarea será asesorar a los directivos de los clubes sobre cuál jugador comprar y cuál no, Renacín desea generar modelos predictivos que evaluén distintas características de los jugadores; todo con el fin de tomar decisiones concretas basadas en los datos.

Sin embargo, su condición de corporeo le impidió tomar la versión anterior de MDS7202, por lo que este motivo Renacín contrata a su equipo para lograr su objetivo final. Dado que aún tiene fuertes vínculos con la dirección de deportes de la municipalidad, el corporeo le entrega base de datos con las estadísticas de cada jugador para que su equipo empieze a trabajar ya con un dataset listo para ser usado.


**Los Datos**

Para este laboratorio deberán trabajar con los csv `statsplayers.csv` y `salarios.pickle`, donde deberán aplicar algoritmos de de aprendizaje supervisado (clasificación y regresión) en base a características que describen de jugadores de futbol.

Para comenzar cargue el dataset señalado y a continuación vea el reporte **`Player_Stats_Report.html`** (adjunto en la carpeta del enunciado) que describe las características principales del `DataFrame`.

In [2]:
# Si usted está utilizando Colabolatory le puede ser útil este código para cargar los archivos.
try:
    from google.colab import drive
    drive.mount("/content/drive")
    path = '/content/drive/MyDrive/lab8'
except: 
    print('Ignorando conexión drive-colab')

Mounted at /content/drive


In [3]:
df_players = pd.read_csv(path+'/stats_players.csv')
df_players

Name          Nationality National_Position Club_Position  \
0      Cristiano Ronaldo             Portugal                LS            LW   
1           Lionel Messi            Argentina                RW            RW   
2                 Neymar               Brazil                LW            LW   
3            Luis Suárez              Uruguay                LS            ST   
4           Manuel Neuer              Germany                GK            GK   
...                  ...                  ...               ...           ...   
17583        Adam Dunbar  Republic of Ireland               NaN           Sub   
17584       Dylan McGoey  Republic of Ireland               NaN           Sub   
17585    Tommy Ouldridge              England               NaN           Res   
17586         Mark Foden             Scotland               NaN           Sub   
17587   Barry Richardson              England               NaN           Sub   

       Height  Weight Preffered_Foot  Age        Work_Rate  Weak_foot  ...  \
0         185      80          Right   32       High / Low          4  ...   
1         170      72           Left   29  Medium / Medium          4  ...   
2         174      68          Right   25    High / Medium          5  ...   
3         182      85          Right   30    High / Medium          4  ...   
4         193      92          Right   31  Medium / Medium          4  ...   
...       ...     ...            ...  ...              ...        ...  ...   
17583     183      82          Right   19  Medium / Medium          1  ...   
17584     185      80          Right   19  Medium / Medium          2  ...   
17585     173      61          Right   18    High / Medium          2  ...   
17586     180      80          Right   21  Medium / Medium          3  ...   
17587     185      77          Right   47  Medium / Medium          2  ...   

       Agility  Jumping  Heading  Shot_Power  Finishing  Long_Shots  Curve  \
0           90       95       85          92         93          90     81   
1           90       68       71          85         95          88     89   
2           96       61       62          78         89          77     79   
3           86       69       77          87         94          86     86   
4           52       78       25          25         13          16     14   
...        ...      ...      ...         ...        ...         ...    ...   
17583       27       56       14          16         13          13     11   
17584       28       53       12          17         12          11     12   
17585       54       61       41          44         28          42     35   
17586       34       48       15          23         14          12     13   
17587       38       51       12          13         11          16     12   

       Freekick_Accuracy  Penalties  Volleys  
0                     76         85       88  
1                     90         74       85  
2                     84         81       83  
3                     84         85       88  
4                     11         47       11  
...                  ...        ...      ...  
17583                 13         15       12  
17584                 13         16       12  
17585                 36         42       37  
17586                 12         24       12  
17587                 11         22       12  

[17588 rows x 39 columns]

## 1.1 Predicción de Seleccionados Nacionales 

Como primera tarea, Renacín, intrigado por la posibilidad de saber qué tan reconocido es un jugador, le consulta a su equipo si es posible predecir si un jugador será o no seleccionado nacional a partir de sus estadísticas en el juego. 

<p align="center">
  <img src="https://thumbs.gfycat.com/ThornyFrankFoxhound-size_restricted.gif" width="500">
</p>

### 1.1.1 Generación de Labels para la Clasificación [Sin Puntaje]


Primero comience generando las labels para la clasificación. Para esto, trabaje sobre el atributo ```National_Position``` suponiendo que los valores nulos son jugadores no seleccionados para representar a su país. 

Hecho esto, ¿Cuantos ejemplos por cada clase se tienen? Comente lo que observa.



**Respuesta:**

A continuación se crea la nueva columna a partir de ```National_Position```, se revisa si el valor es nulo y se iguala a ```False``` para dejar en ```True``` a aquellos que si serían seleccionados y en ```False``` a los que no.

Luego, se transforman a enteros los valores booleanos definidos, quedando:
- **1:** jugador seleccionado
- **0:** jugador no seleccionado

In [4]:
#Se crea la nueva columna a partir de National Position
df_players['Seleccionado'] = df_players['National_Position'].isna()==False
#Se transforman a enteros
df_players['Seleccionado'] = df_players['Seleccionado'].astype(int)

df_players.head(5)

Name Nationality National_Position Club_Position  Height  \
0  Cristiano Ronaldo    Portugal                LS            LW     185   
1       Lionel Messi   Argentina                RW            RW     170   
2             Neymar      Brazil                LW            LW     174   
3        Luis Suárez     Uruguay                LS            ST     182   
4       Manuel Neuer     Germany                GK            GK     193   

   Weight Preffered_Foot  Age        Work_Rate  Weak_foot  ...  Jumping  \
0      80          Right   32       High / Low          4  ...       95   
1      72           Left   29  Medium / Medium          4  ...       68   
2      68          Right   25    High / Medium          5  ...       61   
3      85          Right   30    High / Medium          4  ...       69   
4      92          Right   31  Medium / Medium          4  ...       78   

   Heading  Shot_Power  Finishing  Long_Shots  Curve  Freekick_Accuracy  \
0       85          92         93          90     81                 76   
1       71          85         95          88     89                 90   
2       62          78         89          77     79                 84   
3       77          87         94          86     86                 84   
4       25          25         13          16     14                 11   

   Penalties  Volleys  Seleccionado  
0         85       88             1  
1         74       85             1  
2         81       83             1  
3         85       88             1  
4         47       11             1  

[5 rows x 40 columns]

In [5]:
df_players['Seleccionado'].value_counts()

0    16513
1     1075
Name: Seleccionado, dtype: int64

Se tienen 
- 16.513 jugadores no seleccionados
- 1.075 jugadores seleccionados

Esto era esperable, ya que las selecciones de los países no son tan grandes y por supuesto existen muchos más equipos a los que el resto de los jugadores puede pertenecer.

### 1.1.2 Camino a la clasificación [1 punto]

<p align="center">
  <img src="https://c.tenor.com/SoXZJHWnhKAAAAAC/pitbull-medel.gif" width="500">
</p>

Para preprocesar el dataset, genere un `ColumnTransformer` en donde especifique las transformaciones que hay que realizar para cada columna (por ejemplo StandarScaler, MinMaxScaler, OneHotEncoder, etc...) para que puedan ser utilizadas correctamente por el modelo predictivo y guardelo en algúna variable.

Luego, comente y justifique las transformaciones elegidas sobre cada una de las variables (para esto utilice el material ```Player_Stats_Report.html``` que viene en el zip del lab), al igual que las transformaciones aplicadas.

Hecho lo anterior, **defina al menos 3 pipelines para la clasificación**, en donde utilice el mismo ColumnTransformer definido anteriormente, pero que varie entre cada pipeline los clasificadores. 

Para seleccionar los clasificadores más adecuados, utilice la siguiente guía:

<p align="center">
  <img src="https://scikit-learn.org/stable/_static/ml_map.png" width="500">
</p>

<br/>

Con ella, comente y justifique cada una de las decisiones tomadas al momento de desarrollar su pipeline.

**Nota:** Si tiene problemas al utilizar OneHotEncoder puede utilizar el parámetro handle_unknown='ignore'. Esto hace que en la codificación se omitan las categorias que no aparecen en el entrenamiento. Pregunta dudosa (no tiene puntaje), ¿esto tiene sentido a nivel de modelos?.

**To-Do:**

- [x] Genere un ```ColumnTransformer``` enfocado en preprocesar los datos.
- [x] Indicar y Justificar que preprocesamiento utiliza sobre cada columna.
- [x] Crear 3 ``pipelines`` con diferentes clasificadores.
- [x] Para seleccionar los clasificadores base sus decisiones en la siguiente [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html)
- [x] No entrenar los ``pipelines`` aún.

**Nota:** No es necesario entrenar los clasificadores aún.

In [26]:
ct = ColumnTransformer(
    transformers=[
        ('OneHotEncoder', OneHotEncoder(),  ['Preffered_Foot', 'Work_Rate', 'Weak_foot', 'Skill_Moves']),
        ('StandardScaler', StandardScaler(), ['Height', 'Weight', 'Reactions', 'Balance', 'Agility', 'Jumping']),
        ('MinMax', MinMaxScaler(),['Age', 'Aggression', 'Vision', 'Composure', 'Acceleration', 'Speed', 'Strength','Finishing',
                                   'Long_Shots','Volleys']), 
        ('PowerTransform', PowerTransformer() , ['Ball_Control', 'Dribbling', 'Marking', 'Sliding_Tackle','Standing_Tackle', 
                                                 'Interceptions', 'Crossing', 'Short_Pass', 'Long_Pass', 'Stamina', 'Heading',
                                                 'Shot_Power','Curve', 'Freekick_Accuracy', 'Penalties'])])

Se pre procesaran las columnas del dataframe de la siguiente manera: 

- Aplicación de OneHotEncoding: se aplicó a aquellas columnas categóricas, que tuvieran un número prudente de categorias distintas, estas fueron: 
  - ```'Preffered_Foot'```
  - ```'Work_Rate'```
  - ```'Weak_foot'```
  - ```'Skill_Moves'```  

  No se aplicó ni al nombre, ni al país, ya que son demasiadas categorías y no se considera información relevante al clasificar. Tampoco a ```National_Position``` ni ```Club_Position```, ya que la primera tiene un montón de nulos y se ve expresada en ```Seleccionado``` y la segunda tiene demasiadas categorías posibles distintas.  

- Aplicación de StandarScaler: Se aplicó esta transformación a las columnas que se observó en el reporte que seguían a una distribución similar a la normal, estas fueron: 
  - ```'Height'``` 
  - ```'Weight'``` 
  - ```'Reactions'```
  - ```'Balance'```
  - ```'Agility'```
  - ```'Jumping'```

- Aplicación de MinMaxScaler: Se aplicó a aquellas columnas numéricas, cuya distribución no fuera tan similar a una normal, pero tampoco tan distante, estas fueron:
  - ```'Age'```
  - ```'Aggression'```
  - ```'Vision'```
  - ```'Composure'```
  - ```'Acceleration'```
  - ```'Speed'```
  - ```'Strength'```
  - ```'Finishing'```
  - ```'Long_Shots'```
  - ```'Volleys'```

- Aplicación de PowerTransform: Se aplicó a aquellas columnas con una distribución muy diferente a la normal, las escogidas fueron:
  - ```'Ball_Control'```
  - ```'Dribbling'```
  - ```'Marking'```
  - ```'Sliding_Tackle'```
  - ```'Standing_Tackle'```
  - ```'Interceptions'```
  - ```'Crossing'```
  - ```'Short_Pass'```
  - ```'Long_Pass'```
  - ```'Stamina'```
  - ```'Heading'```
  - ```'Shot_Power'```
  - ```'Curve'```
  - ```'Freekick_Accuracy'```
  - ```'Penalties'```

**Respuesta:**

Siguiendo la guía entregada, se realizóel siguiente camino:
- más de 50 muestras
- prediciendo categorías
- data etiquetada
- menos de 100K muestras, así quedaron las siguientes opciones en orden:
  - Linear SCV
  - KNeighbors Classifier
  - SCV
  - Ensemble Classifiers  

Por lo que se utilizaron los primeros 3 para realizar los pipelines.

In [7]:
#Se crean los clasificadores
L_svc = LinearSVC()
knn = KNeighborsClassifier()
svc = SVC()

#Se crea un pipeline para cada transformador
pipe_L_svc = Pipeline([("ColumnTransformer", ct),("LinearSVC", L_svc)])
pipe_knn = Pipeline([("ColumnTransformer", ct),("KNeighbors", knn)])
pipe_svc = Pipeline([("ColumnTransformer", ct),("SVC", svc)])

### 1.1.3 Entrenemos los pipelines [1 punto]

<p align="center">
  <img src="https://i.gifer.com/7Cc8.gif" width="350">
</p>


Ahora, entrene los `pipeline` generados en los pasos anteriores. Para esto, primero separe los datos de entrenamiento en un conjunto de entrenamiento y de prueba  (la proporción queda a su juicio).

En este paso, seleccione los ejemplos de forma aleatoria e intente mantener la distribución original de labels de cada clase en los conjuntos de prueba/entrenamiento. (vea la documentación de `train_test_split`).


Luego, entrene los pipelines

Una vez entrenado su modelo, evalue su rendimiento a través de diferentes métricas, comentando que significa cada uno de los valores obtenidos. Puede usar la función `classification_report` para corroborar sus resultados.

- ¿Qué implican los valores de accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional)?
- ¿Podrían mejorarse los resultados?, ¿Cómo?
- ¿Influye la cantidad de ejemplos por clase?

**To-Do**:

- [x] Separar el conjunto de datos en entrenamiento y de prueba.
- [x] Entrenar los `pipelines`.
- [x] Utilizar las métricas para evaluar los modelos generados.
- [x] Responder preguntas

**Respuesta:**

In [8]:
from sklearn.model_selection import train_test_split
y = df_players['Seleccionado']
X = df_players.drop(columns=['Seleccionado'])


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [9]:
y_train.value_counts(), y_test.value_counts()

(0    11052
 1      731
 Name: Seleccionado, dtype: int64,
 0    5461
 1     344
 Name: Seleccionado, dtype: int64)

In [10]:
11052/731, 5461/344

(15.119015047879618, 15.875)

Para ambos conjuntos la proporción de no_seleccionados/seleccionados se encuentra entre 15 y 16, por lo que nos parece que las proporciones se mantienen de manera correcta.

In [11]:
#Se entrenan los 3 clasificadores
pipe_L_svc.fit(X_train, y_train)
pipe_knn.fit(X_train, y_train)
pipe_svc.fit(X_train, y_train)

#Se predice con los 3 clasificadores
y_Lsvc = pipe_L_svc.predict(X_test)
y_knn = pipe_knn.predict(X_test)
y_svc = pipe_svc.predict(X_test)


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [12]:
print('Clasificación por Linear SVC')
print("Matriz de confusión\n", confusion_matrix(y_Lsvc, y_test))
print(classification_report(y_test, y_Lsvc))

Clasificación por Linear SVC
Matriz de confusión
 [[5461  343]
 [   0    1]]
              precision    recall  f1-score   support

           0       0.94      1.00      0.97      5461
           1       1.00      0.00      0.01       344

    accuracy                           0.94      5805
   macro avg       0.97      0.50      0.49      5805
weighted avg       0.94      0.94      0.91      5805



In [13]:
print('Clasificación por KNeighbors Classifier')
print("Matriz de confusión\n", confusion_matrix(y_knn, y_test))
print(classification_report(y_test, y_knn))

Clasificación por KNeighbors Classifier
Matriz de confusión
 [[5430  313]
 [  31   31]]
              precision    recall  f1-score   support

           0       0.95      0.99      0.97      5461
           1       0.50      0.09      0.15       344

    accuracy                           0.94      5805
   macro avg       0.72      0.54      0.56      5805
weighted avg       0.92      0.94      0.92      5805



In [14]:
print('Clasificación por SVC')
print("Matriz de confusión\n", confusion_matrix(y_svc, y_test))
print(classification_report(y_test, y_svc))

Clasificación por SVC
Matriz de confusión
 [[5461  343]
 [   0    1]]
              precision    recall  f1-score   support

           0       0.94      1.00      0.97      5461
           1       1.00      0.00      0.01       344

    accuracy                           0.94      5805
   macro avg       0.97      0.50      0.49      5805
weighted avg       0.94      0.94      0.91      5805



**Respuesta**:

**¿Qué implican los valores de accuracy, precisión y recall de la clase positiva (la que indica que un jugador es seleccionado nacional)?**

- El accuracy representa la cantidad de predicciones correctas en el total de predicciones, se observa que tiene un valor de 0.94 lo que parecería bueno, pero esto es sólo gracias al gran desbalance de las clases, ya que al predecir sólo 0 y equivocarse en los 1, se obtiene esta métrica alta.

- La precisión nos dice "de los valores que predijo el modelo como 0/1 ¿cuántos realmente eran 0/1?" Así, en el caso de la clase positiva, nos dice cuántos de los jugadores que el modelo predijo que serían seleccionados, realmente lo fueron.
  - Para los modelos a partir de SVM se obtuvo un valor ```precision``` de ```1.00```, lo que haría pensar que el modelo es bueno, pero esto es engañoso, ya que el modelo sólo predijo que **uno** de los jugadores sería seleccionado y lo hizo correctamete, pero esta métrica no nos dice nada de si habían otros seleccionados que no fueron identificados.
  - Para el modelo basado en KNN se obtuvo un valor de ```0.5```, en este caso, se predijeron más valores como seleccionados (62) y la mitad de ellos fue predicha correctamente.

- Finalmente, el recall nos dice "¿Qué porcentaje de los seleccionados son identificados por el modelo?" Con esta métrica podemos observar la falla de los modelos entrenados.
  - Para los modelos basados en SVM se obtuvo un ```recall```de ```0.00```es decir que en porcentajes, se identificó un 0\% de los jugadores seleccionados. 
  - Para el modelo basado en KNN mejora un poco, se logró identificar un 0.09\% de los jugadores seleccionados.


**¿Podrían mejorarse los resultados?, ¿Cómo?**

Para mejorar los resultados se podrían seguir algunas de las siguientes estrategias:
- Aplicar *oversampling* o *subsampling* de modo que el desbalance en las clases no afecte tanto a los modelos utilizados. Se debe tener cuidado con este enfoque.
- Encontrar mejores valores para los hiperparámetros de los modelos utilizados, ya que en esta ocasión se utilizaron simplemente los valores por defecto. De este modo se podría ajustar la sensibilidad del modelo ante el desbalance. 

**¿Influye la cantidad de ejemplos por clase?**

Por supuesto que si, como ya se venía adelentando, el mal desempeño de estos modelos se debe principalmente al gran desbalance entre las clases, ya que los modelos son sensibles a esta. Lo que no significa que los modelos utilizados sean malos, sólo que en su busqueda de equivocarse lo menos posible, terminan prefiriendo elegir en casi todos los casos a la clase mayoritaria, en este caso, que el jugador no será seleccionado.

## 1.2 Predicción de posiciones de jugadores [2 puntos]

<p align="center">
  <img src="https://pbs.twimg.com/media/E1rfA1aWEAYU6Ny.jpg" width="500">
</p>

En una nueva jornada de desmesuradas transacciones deportivas, Renacín escuchó a sus colegas discutir acerca de que el precio de cada jugador depende en gran medida de la posición en la cancha en la que juega. Y además, que hay bastantes jugadores nuevos que no tienen muy claro en que posición verdaderamente brillarían, por lo que actualmente puede que actualmente estén jugando en posiciones sub-optimas. 

Viendo que los resultados del primer análisis no son tan esperanzadores, el corporeo los comanda a cambiar su tarea: ahora, les solicita que construyan un clasificador enfocado en predecir la mejor posición de los jugadores en la cancha según sus características. 

Para lograr esto, primero, les pide que etiqueten de la siguiente manera los valores que aparecen en el atributo ```Club_Position```, pidiendo que agrupen los valores en los siguientes grupos:

**Nota**:  Renacín les recalca que **no deben utilizar los valores ```Sub``` y ```Res``` de esta columna**.

```python
ataque = ['ST', 'CF'] 
central_ataque = ['RW', 'CAM', 'LW'] 
central = ['RM', 'CM', 'LM'] 
central_defensa = ['RWB', 'CDM', 'LWB']
defensa = ['RB', 'CB', 'LB']
arquero = ['GK']
```

Cabe señalar que al igual como lo realizado con la clasificación binaria, deberá justificar en base a la [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html) la elección del clasificador y se deben comentar los resultados obtenidos en la clasificación.

**Nota:** Clasifique solamente con las clases señaladas, si observa mas clases eliminelas de la clasficación.

**To-Do**:

- [x] Aplique las etiquetas descritas anteriormente en cada uno de los valores señalados en esta sección.
- [x] Cuente cuantos por clase quedan.
- [x] Entrene el nuevo pipeline y ejecute una evaluación de este.  
- [x] Comente los resultados obtenidos.

**Respuesta:**

In [16]:
#Aplicar etiquetas
posiciones = {'ST':'ataque',
              'CF':'ataque',
              'RW':'central_ataque',
              'CAM':'central_ataque',
              'LW':'central_ataque',
              'RM':'central',
              'CM':'central',
              'LM':'central',
              'RWB':'central_defensa',
              'CDM':'central_defensa',
              'LWB':'central_defensa',
              'RB':'defensa',
              'CB':'defensa',
              'LB':'defensa',
              'GK':'arquero'}

df_players['Club_Position'] = df_players['Club_Position'].map(posiciones)

df_players.dropna(subset=['Club_Position'], inplace=True)

In [17]:
#Cuenta de cuántos quedan por clase
df_players['Club_Position'].value_counts()

defensa            1180
central             907
arquero             632
central_ataque      581
ataque              430
central_defensa     209
Name: Club_Position, dtype: int64

Observando la guía, se decide el clasificador multiclases a utilizar de la siguiente manera:

- más de 50 muestras
- prediciendo categorías
- data etiquetada
- menos de 100K muestras, así quedaron las siguientes opciones en orden:
  - Linear SCV
  - KNeighbors Classifier
  - SCV
  - Ensemble Classifiers  

Dado que el camino es el mismo que el anterior, se decide utilizar la opción que anteriormente se dejó fuera *Ensamble Classifiers*, en particular la opción de Random Forest, ya que es la que suena más conocida.



In [18]:
from sklearn.ensemble import RandomForestClassifier

#Se crea el clasificador
rfc = RandomForestClassifier()

#Se crea un pipeline para cada transformador
pipe_rf = Pipeline([("ColumnTransformer", ct),("RandomForest", rfc)])

In [19]:
y = df_players['Club_Position']
X = df_players.drop(columns=['Club_Position'])


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [20]:
#Se entrena el clasificador
pipe_rf.fit(X_train, y_train)

#Se predice con los 3 clasificadores
y_rf = pipe_rf.predict(X_test)

In [21]:
print('Clasificación por Random Forest')
print("Matriz de confusión\n", confusion_matrix(y_rf, y_test))
print(classification_report(y_test, y_rf))

Clasificación por Random Forest
Matriz de confusión
 [[200   0   0   0   0   0]
 [  0 122  16  13   0   0]
 [  0  16 210 113   8   5]
 [  0   7  38  50   5   2]
 [  0   0   6   1  15   5]
 [  0   0  46   6  40 376]]
                 precision    recall  f1-score   support

        arquero       1.00      1.00      1.00       200
         ataque       0.81      0.84      0.82       145
        central       0.60      0.66      0.63       316
 central_ataque       0.49      0.27      0.35       183
central_defensa       0.56      0.22      0.32        68
        defensa       0.80      0.97      0.88       388

       accuracy                           0.75      1300
      macro avg       0.71      0.66      0.67      1300
   weighted avg       0.73      0.75      0.73      1300



**Respuesta**:

En el recuento de jugadores en cada clase se puede observar que nuevamente existe el problema de desbalance de clases, ya que la mayoría de los jugadores son ```defensa``` o ```central``` y muy pocos son la mezcla ```central_defensa```. 

Es por ello que nuevamente se observan métricas altas de precision y recall en las clases mayoritarias. Por otra parte, se puede notar en la matriz de confusión que el modelo confunde entre clases seguidas (esto ya que si bien no es diagonal perfecta, es bastante "diagonal") lo que se puede deber a que el perfil de un jugador ```central``` es muy similar al de un jugador ```central_ataque```o ```central_defensa```, este último se predijo bastante mal, debido a su desbalance y a que era confundido con los otros. 

Es por esta misma razón que creemos que la única clase que se predijo completamente a la perfección fue la de ```arquero```, ya que son un tipo de jugador muy diferente al resto y esto se nota en sus estadísticas.

Respecto a si se pueden mejorar los resultados, se cree que si, aplicando las mismas estrategias mencionadas anteriormente:
- Seleccionar mejores hiperparámetros
- Aplicar estrategias de *subsampling* u *oversampling*
- Utilizar otro clasificador, también especializado en clasificación multiclase.


## 1.3 Predicción de Sueldos [2 puntos]

<p align="center">
  <img src="https://media.giphy.com/media/3oEjHWtHAFcOKS4iA0/giphy.gif" width="460">
</p>

Queriendo ahondar aún más en el mercado del balompíe, Renacin, logra obtener (de una manera no muy formal) los sueldos de múltiples futbolistas y los guarda en el archivo ```sueldos.csv```. Con ellos les solicita que generen un regresor que les permita predecir el sueldo de los futbolistas en base a las características de los pichichis, esto, debido a su motivación por invertir y/o realizar especulación sobre los sueldos de jugadores.

Renacin es claro señalando que deben seguir utilizando la [guía](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html) y comenten cada uno de los pasos realizados, para obtener su regresión lineal. Señalándoles que no aceptara un $R^2$ inferior a 0.35 para el modelo solicitado.

Para esta parte usted tiene total libertad en la generación del regresor, la unica exigencia es que utilice un pipeline para generar la regresión y utilice la metrica $R^2$ para medir el rendimiento de esta.

**To-Do**:

- [x] Explique en que consiste la métrica $R^2$
- [x] Generar un pipeline para la regresión.
- [x] Obtener un regresor con un $R^2$ superior a  $0.35$.
- [ ] Comente sus resultados y si es posible mejorar los resultados obtenidos. ¿Se necesitarían más datos o otros tipos de características o una combinación de ambos?

**Respuesta**

**Explique en que consiste la métrica $R^2$**

La métrica $R^{2}$ nos dice qué porcentaje de la variabilidad de los datos que se están prediciendo, se logra explicar con el modelo propuesto para la regresión. Esto ya que se construye como la variabilidad de la estimación dividida por la variabilidad total en los datos (se cumple que la variabilidad total es igual a la suma de la variabilidad de la estimación más la del error). 


  

Lo primero que se debe realizar es cargar los datos de los sueldos:

In [22]:
df_sueldos = pd.read_csv(path+'/salarios.csv')
#df_sueldos

Unnamed: 0             Player  Weekly Salary
0           1528       Lionel Messi      1538905.0
1           1006  Cristiano Ronaldo      1248536.0
2           1529  Antoine Griezmann       997032.0
3           2004             Neymar       797726.0
4           1530        Gareth Bale       607706.0
...          ...                ...            ...
2529        1527    Simone Ghidotti          283.0
2530        2539   Valentin Gendrey          100.0
2531        1001        John Yeboah           70.0
2532        1000    Antonis Aidonis           70.0
2533        1002        Leon Dajaku           70.0

[2534 rows x 3 columns]

Se realiza un join entre este dataset nuevo y con el que se trabajó las partes anteriores, para así tener la relación entre las características de un jugador y su salario. Se realiza un inner join para evitar valores nulos.

In [23]:
df = df_players.merge(df_sueldos,
                      left_on=["Name"],
                      right_on=["Player"],
                      how="inner")
#df

Name Nationality National_Position   Club_Position  Height  \
0    Cristiano Ronaldo    Portugal                LS  central_ataque     185   
1         Lionel Messi   Argentina                RW  central_ataque     170   
2               Neymar      Brazil                LW  central_ataque     174   
3          Luis Suárez     Uruguay                LS          ataque     182   
4         Manuel Neuer     Germany                GK         arquero     193   
..                 ...         ...               ...             ...     ...   
573     Dennis Lippert     Germany               NaN         defensa     172   
574     Charles Traoré        Mali               NaN         defensa     180   
575        Will Norris     England               NaN         arquero     191   
576      Harvey Barnes     England               NaN  central_ataque     179   
577    Pontus Dahlberg      Sweden               NaN         arquero     194   

     Weight Preffered_Foot  Age        Work_Rate  Weak_foot  ...  Finishing  \
0        80          Right   32       High / Low          4  ...         93   
1        72           Left   29  Medium / Medium          4  ...         95   
2        68          Right   25    High / Medium          5  ...         89   
3        85          Right   30    High / Medium          4  ...         94   
4        92          Right   31  Medium / Medium          4  ...         13   
..      ...            ...  ...              ...        ...  ...        ...   
573      63           Left   21  Medium / Medium          3  ...         25   
574      74           Left   25     Medium / Low          2  ...         30   
575      76           Left   23  Medium / Medium          3  ...         10   
576      68           Left   19  Medium / Medium          3  ...         50   
577      84          Right   18  Medium / Medium          3  ...          5   

     Long_Shots  Curve  Freekick_Accuracy  Penalties  Volleys  Seleccionado  \
0            90     81                 76         85       88             1   
1            88     89                 90         74       85             1   
2            77     79                 84         81       83             1   
3            86     86                 84         85       88             1   
4            16     14                 11         47       11             1   
..          ...    ...                ...        ...      ...           ...   
573          40     49                 26         28       23             0   
574          32     38                 40         45       29             0   
575          10     17                 18         16       12             0   
576          52     56                 52         49       50             0   
577           9     10                 11         12        9             0   

     Unnamed: 0             Player  Weekly Salary  
0          1006  Cristiano Ronaldo      1248536.0  
1          1528       Lionel Messi      1538905.0  
2          2004             Neymar       797726.0  
3          1531        Luis Suárez       508923.0  
4           498       Manuel Neuer       326233.0  
..          ...                ...            ...  
573         991     Dennis Lippert          620.0  
574        2229     Charles Traoré        13289.0  
575         485        Will Norris         3958.0  
576         463      Harvey Barnes        13193.0  
577         483    Pontus Dahlberg         3958.0  

[578 rows x 43 columns]

La nueva columna de salarios tiene valores muy grandes, por lo que debe ser transformada, dado que se trata de dinero, se utilizará una transformación logaritmica que es la más recomendada en estos casos.

In [24]:
df['Weekly Salary'] = np.log(df['Weekly Salary'])

#df

Name Nationality National_Position   Club_Position  Height  \
0    Cristiano Ronaldo    Portugal                LS  central_ataque     185   
1         Lionel Messi   Argentina                RW  central_ataque     170   
2               Neymar      Brazil                LW  central_ataque     174   
3          Luis Suárez     Uruguay                LS          ataque     182   
4         Manuel Neuer     Germany                GK         arquero     193   
..                 ...         ...               ...             ...     ...   
573     Dennis Lippert     Germany               NaN         defensa     172   
574     Charles Traoré        Mali               NaN         defensa     180   
575        Will Norris     England               NaN         arquero     191   
576      Harvey Barnes     England               NaN  central_ataque     179   
577    Pontus Dahlberg      Sweden               NaN         arquero     194   

     Weight Preffered_Foot  Age        Work_Rate  Weak_foot  ...  Finishing  \
0        80          Right   32       High / Low          4  ...         93   
1        72           Left   29  Medium / Medium          4  ...         95   
2        68          Right   25    High / Medium          5  ...         89   
3        85          Right   30    High / Medium          4  ...         94   
4        92          Right   31  Medium / Medium          4  ...         13   
..      ...            ...  ...              ...        ...  ...        ...   
573      63           Left   21  Medium / Medium          3  ...         25   
574      74           Left   25     Medium / Low          2  ...         30   
575      76           Left   23  Medium / Medium          3  ...         10   
576      68           Left   19  Medium / Medium          3  ...         50   
577      84          Right   18  Medium / Medium          3  ...          5   

     Long_Shots  Curve  Freekick_Accuracy  Penalties  Volleys  Seleccionado  \
0            90     81                 76         85       88             1   
1            88     89                 90         74       85             1   
2            77     79                 84         81       83             1   
3            86     86                 84         85       88             1   
4            16     14                 11         47       11             1   
..          ...    ...                ...        ...      ...           ...   
573          40     49                 26         28       23             0   
574          32     38                 40         45       29             0   
575          10     17                 18         16       12             0   
576          52     56                 52         49       50             0   
577           9     10                 11         12        9             0   

     Unnamed: 0             Player  Weekly Salary  
0          1006  Cristiano Ronaldo      14.037482  
1          1528       Lionel Messi      14.246582  
2          2004             Neymar      13.589520  
3          1531        Luis Suárez      13.140052  
4           498       Manuel Neuer      12.695367  
..          ...                ...            ...  
573         991     Dennis Lippert       6.429719  
574        2229     Charles Traoré       9.494692  
575         485        Will Norris       8.283494  
576         463      Harvey Barnes       9.487442  
577         483    Pontus Dahlberg       8.283494  

[578 rows x 43 columns]

Se utilizará el mismo column transform que en las partes anteriores, ya que la nueva información corresponde a la columna objetivo, por lo que no se introduce al pipeline.  

Para elegir la regresión a utilizar en el pipeline, se mira la guía, se sigue el siguiente camino:

- más de 50 muestras
- prediciendo cantidades
- menos de 100K muestras, así quedaron las siguientes opciones en orden:
  - RidgeRegressions
  - SVR
  - SVR(kernel='rbf')
  - Ensemble Regressors

Se decide utilizar SVR con kernel gaussiano.

In [48]:
### Código aquí ###
from sklearn.svm import SVR

#Se crea el clasificador
svr = SVR(kernel='linear')

#Se crea un pipeline
pipe_svr = Pipeline([("ColumnTransformer", ct),("SVR", svr)])

Con el pipeline creado, ya podemos dividir el dataset en entrenamiento y prueba, para luego entrenar y observar el desempeño del modelo generado.

In [49]:
#Se divide el dataset
y = df['Weekly Salary']
X = df.drop(columns=['Weekly Salary'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=17)

In [51]:
#Se entrena el clasificador
pipe_train = pipe_svr.fit(X_train, y_train)

#Se obtiene el R2
R2 = str(pipe_train.score(X_test,y_test))

print('El R cuadrado del modelo generado es: '+ R2 )

El R cuadrado del modelo generado es: 0.502556996907602


In [59]:
X_test['Salary predicho'] = pipe_train.predict(X_test)
X_test['Weekly Salary'] = y_test
fig = px.histogram(X_test, x=['Weekly Salary','Salary predicho'], barmode = "group")
fig.show()

**Respuesta**:

```
Comente de resultados observados y si es posible mejorar los resultados.
```

Se obtuvo un modelo con un $R^{2}$ de 0.50, lo cual significa que un 50\% de la variabilidad del salario de los futbolistas, es explicada por nuestro modelo y el otro 50\% se explica por cosas que el modelo no considera, por ejemplo algunos atributos que no se hayan introducido o simplemente no se haya tenido información.  
Además se generó un histograma para comparar el comportamiento de los salarios predichos y reales en el conjunto de prueba, si bien hay barras en que los valores difieren bastante, el comportamiento de la distribución si se captura bastante bien en el modelo generado.  

Se cree que es posible mejorar los resultados, para esto se podría
- Buscar formas de integrar las columnas que se dejaron fuera, a modo de integrar esta información.
- Considerar un pre-procesamiento distinto de las columnas que pudiera permitir un mejor aprovechamiento de los datos que se tienen.
- Buscar otras fuentes de datos.
- Mezclar las columnas que se tienen por si existen efectos potenciados (por ejemplo, mezclar posición-altura)

```
¿Se necesitarían más datos o otros tipos de características o una combinación de ambos?
```
Se necesitarían principalmente otros tipos de características que aporten la información que en este momento no se tiene. De todas formas una mayor cantidad de datos (con la mayor calidad posible) tampoco haría daño. Se debe considerar además, cambiar el $R^{2}$ por el $R^{2} ajustado$, para evitar que su valor aumente sólo por tener más columnas.


# Conclusión
Eso ha sido todo para el lab de hoy, recuerden que el laboratorio tiene un plazo de entrega de una semana. Cualquier duda del laboratorio, no duden en contactarnos por mail o U-cursos.

<p align="center">
  <img src="https://media2.giphy.com/media/l1J3CbFgn5o7DGRuE/giphy.gif">
</p>

<br>
<center>
<img src="https://i.kym-cdn.com/photos/images/original/001/194/195/b18.png" width=100 height=50 />
</center>
<br>

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=87110296-876e-426f-b91d-aaf681223468' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>